#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#             
# simple quicklaunch menu using dmenu

options=$(ls -1 ~/Scripts/dmenu)
path="~/Scripts/dmenu/"

choise=$(echo -e "$options" | dmenu -i -l 5) # using "$options" instead of $options to get multi line

exec $path$choise
