#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#             
# simple shortcut menu using dmenu

options1="Reset i3 screens\nRestart polybar\nRefresh wallpaper\nToggle compton\nScreen settings"
options2=$(ls -1 ~/Scripts/dmenu)

options="$options2\n$options1"

path="~/Scripts/dmenu/"


choise=$(echo -e "$options" | dmenu -i -l 8) # using "$options" instead of $options to get multi line

if test "$choise" = "Restart polybar"; then
	$HOME/.config/polybar/launch.sh
elif test "$choise" = "Refresh wallpaper"; then
	$HOME/Scripts/randwallpaper.sh
elif test "$choise" = "Toggle compton"; then
	$HOME/.config/compton/toggle.sh
elif test "$choise" = "Screen settings"; then
	lxrandr
elif test "$choise" = "Reset i3 screens"; then
	i3-workscreen
else
	exec $path$choise
fi
