#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#             
# simple shortcut menu using dmenu

options="Restart polybar\nRefresh wallpaper\nToggle compton"

choise=$(echo -e "$options" | dmenu -i -l 20) # using "$options" instead of $options to get multi line

if test "$choise" = "Restart polybar"; then
	$HOME/.config/polybar/launch.sh
elif test "$choise" = "Refresh wallpaper"; then
	$HOME/Scripts/randwallpaper.sh
elif test "$choise" = "Toggle compton"; then
	$HOME/.config/compton/toggle.sh
fi
