#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#             
# simple script to add some pacman info to the bar

echo 📥$(pacman -Qu | wc -l): 📦$(pacman -Q | wc -l)
