#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#
# simple script to add the volume to the bar

volume=$(amixer get Master | awk '/Front Left:/ {print $5}' | tr -d '[%]')

if [[ $volume -le 1 ]]; then
	icon="🔇"
	echo $icon
else
	icon="🔊"
	echo $icon$volume"%"
fi
