#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#
# simple script to add the volume to the bar

volume=$(pamixer --get-volume)

if [[ $volume -le 1 ]]; then
	icon="🔇"
	echo $icon
else
	icon="🔊"
	echo $icon$volume"%"
fi
