#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#
# simple script to add the volume to the bar

status=$(pamixer --get-mute)
volume=$(pamixer --get-volume)

if [[ $status == 'true' ]]; then
	icon="🔇"
	echo $icon
else
	icon="🔊"
	echo $icon$volume"%"
fi
