#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#             
# simple menu to choose volume source using dmenu

choise=$(pamixer --list-sources | sed '1d;2d' | dmenu -i -l 2 | awk '{print $1}')

pamixer --sink $choise
pamixer --source $choise

export AUDIO=$choise
