#!/bin/sh
# ____  ____  
#| __ )| __ ) 
#|  _ \|  _ \ 
#| |_) | |_) |
#|____/|____/ 
#             
# simple quicklaunch menu using dmenu

choise=$(echo -e "inkscape\nvscodium\nbrowser\nfirefox\nthunar\nranger\nmessenger\nwhatsapp\noverleaf\ntoledo\nGoogle drive\nzoom" | dmenu -i -l 20)

if [[ $choise == "ranger" ]];then 
	$TERM -e ranger
elif [[ $choise == "toledo" ]];then
	$BROWSER toledo.kuleuven.be
elif [[ $choise == "messenger" ]];then
	$BROWSER messenger.com
elif [[ $choise == "whatsapp" ]];then
	$BROWSER web.whatsapp.com
elif [[ $choise == "overleaf" ]];then
	$BROWSER overleaf.com
elif [[ $choise == "Google drive" ]];then
	$BROWSER drive.google.com/drive
elif [[ $choise == "browser" ]];then
	$BROWSER
else
	$choise
fi
